name: Add Labels

on:
  pull_request:
    types: opened

jobs:
  label_pulls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.addLabels({
              labels: ["xenon"]
            })
